version: '3'

services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=backenddb
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=backend
